base_url = "https://ritiek.github.io"
title = "Ritiek Malhotra"
description = "Just some of my adventures!"
theme = "adidoks"

default_language = "en"
compile_sass = true
minify_html = false
build_search_index = true
generate_feeds = true

taxonomies = [
  {name = "tags"},
]

[link_checker]
skip_anchor_prefixes = ["#"]

[search]
include_title = true
include_description = false
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true

[extra]
author = "Ritiek Malhotra"
github = "https://github.com/ritiek"
email = "ritiekmalhotra123@gmail.com"

language_code = "en-US"
theme_color = "#fff"
title_separator = "|"
title_addition = ""

timeformat = "%d %b %Y"
timezone = "UTC"

# Font settings to match original Jekyll site
font_family = "PT Serif"
font_family_headings = "PT Serif"
font_family_body = "PT Sans"

# Social links
social_links = [
    { name = "GitHub", url = "https://github.com/ritiek", icon = "github" },
    { name = "Stack Overflow", url = "https://stackoverflow.com/users/6554943/ritiek", icon = "stack-overflow" },
    { name = "Reddit", url = "https://www.reddit.com/user/Ritiek", icon = "reddit" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/ritiek", icon = "linkedin" },
    { name = "Email", url = "mailto:ritiekmalhotra123@gmail.com", icon = "envelope" },
    { name = "Matrix", url = "https://matrix.to/#/@ritiek:matrix.org", icon = "comments" },
    { name = "RSS", url = "/atom.xml", icon = "rss" }
]

edit_page = false
math = false

[[extra.menu.main]]
name = "Archive"
section = "posts"
url = "posts"
weight = 4

[[extra.menu.main]]
name = "About"
section = "about"
url = "about"
weight = 5



[extra.open]
enable = true
twitter_site = ""
twitter_creator = ""
facebook_author = ""
facebook_publisher = ""
og_locale = "en_US"

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/ritiek"
weight = 10

[[extra.menu.social]]
name = "Stack Overflow"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20h20"/><path d="M4 16h16"/><path d="M6 12h12"/><path d="M8 8h8"/><path d="M10 4h4"/></svg>'
url = "https://stackoverflow.com/users/6554943/ritiek"
weight = 20

[[extra.menu.social]]
name = "Reddit"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="9" cy="10" r="1"/><circle cx="15" cy="10" r="1"/><path d="M9 15c.5.7 1.5 1 3 1s2.5-.3 3-1"/></svg>'
url = "https://www.reddit.com/user/Ritiek"
weight = 30

[[extra.menu.social]]
name = "LinkedIn"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg>'
url = "https://www.linkedin.com/in/ritiek"
weight = 40

[[extra.menu.social]]
name = "RSS"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 11a9 9 0 0 1 9 9"/><path d="M4 4a16 16 0 0 1 16 16"/><circle cx="5" cy="19" r="1"/></svg>'
url = "/atom.xml"
weight = 50

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org/">Zola</a>'
